#!/usr/bin/expect

set host 192.168.33.12
spawn bundle exec serverspec-init
expect "OS type"
expect "number"
send "1\n"
expect "backend type"
expect "number"
send "1\n"
expect "Vagrant"
send "n\n"
expect "target host"
send "$host\n"
expect eof
